version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3030:3030
    command: npm run start:staging
    env_file:
      - .staging.env
    networks:
      - webnet
    depends_on:
      - redis

  redis:
    image: redis:6.0.6-alpine
    command: ["sh", "-c", "exec redis-server"]
    ports:
      - 6379:6379
    networks:
      - webnet

networks:
  webnet: